In [178]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings
warnings.filterwarnings('ignore')

In [179]:
df=sns.load_dataset("iris")

In [180]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [181]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [182]:
df['species'].unique()

<ArrowStringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [183]:
from sklearn.model_selection import train_test_split

In [184]:
X=df.drop('species', axis=1)
y=df['species']

In [185]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [186]:
from sklearn.neighbors import KNeighborsClassifier

In [187]:
model_knn=KNeighborsClassifier(n_neighbors=13)

In [188]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [189]:
model_knn.score(X_test, y_test)

1.0

In [190]:
from sklearn.svm import SVC

In [191]:
model_svm=SVC(gamma='auto')

In [192]:
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [193]:
model_svm.score(X_test, y_test)

1.0

## Now Let's Use Grid Search CV

In [194]:
from sklearn.model_selection import GridSearchCV

In [195]:
classifier = GridSearchCV((model_svm), {
    'C':[10, 20, 30],
    'kernel':['rbf', 'linear']
}, cv =5, return_train_score=False)

In [196]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [10, 20, 30], 'kernel': ['rbf', 'linear']})

In [197]:
classifier.cv_results_

{'mean_fit_time': array([0.00253611, 0.00216942, 0.0030436 , 0.00296278, 0.00173149,
        0.00158348]),
 'std_fit_time': array([1.61044040e-04, 4.80308472e-04, 5.68972847e-04, 4.10126013e-04,
        1.42403775e-04, 6.82133180e-05]),
 'mean_score_time': array([0.00164738, 0.00141239, 0.00188498, 0.00163507, 0.00117073,
        0.00101871]),
 'std_score_time': array([2.73650526e-05, 3.38715428e-04, 5.38646520e-04, 3.35874055e-04,
        1.15220534e-04, 3.81607984e-05]),
 'param_C': masked_array(data=[10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 1.        , 0.96666667, 1.        , 0.96666667,
        1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.9       , 0.9       , 0.9       , 0.9       ,
        0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.93333333,
        0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.97333333, 0.96666667, 0.96666667, 0.96      ,
        0.96      ]),
 'std_test_score': array([0.01632993, 0.03887301, 0.03651484, 0.0421637 , 0.03887301,
        0.04898979]),
 'rank_test_score': array([1, 2, 3, 4, 5, 5], dtype=int32)}

In [198]:
results=pd.DataFrame(classifier.cv_results_)

In [199]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002536,0.000161,0.001647,0.000027,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002169,0.000480,0.001412,0.000339,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
2,0.003044,0.000569,0.001885,0.000539,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
3,0.002963,0.000410,0.001635,0.000336,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
4,0.001731,0.000142,0.001171,0.000115,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,5
5,0.001583,0.000068,0.001019,0.000038,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,5

In [200]:
results[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       10       linear         0.973333
2       20          rbf         0.966667
3       20       linear         0.966667
4       30          rbf         0.960000
5       30       linear         0.960000

In [201]:
from sklearn.model_selection import RandomizedSearchCV

In [202]:
classifier_r = RandomizedSearchCV((model_svm), {
    'C':[10, 20, 30],
    'kernel':['rbf', 'linear']
},n_iter=4, cv =5, return_train_score=False)

In [203]:
classifier_r.fit(X, y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [204]:
classifier_r.cv_results_

{'mean_fit_time': array([0.00195837, 0.00202718, 0.00196204, 0.00176902]),
 'std_fit_time': array([3.39688129e-04, 4.01704105e-05, 7.14483798e-05, 5.77491732e-05]),
 'mean_score_time': array([0.00130863, 0.00138965, 0.0013186 , 0.00117464]),
 'std_score_time': array([1.40349418e-04, 2.95271953e-05, 3.88007761e-05, 2.19222740e-05]),
 'param_kernel': masked_array(data=['rbf', 'rbf', 'rbf', 'linear'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[30, 10, 20, 20],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 30},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'rbf', 'C': 20},
  {'kernel': 'linear', 'C': 20}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667, 0.9       , 0.9       ]),
 'split3_test_score': array([0.93333333, 0.96666667, 0.96666667, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1.]),
 'mean_test_score': array([0.96      , 0.98      , 0.96666667, 0.96666667]),
 'std_test_score': array([0.03887301, 0.01632993, 0.03651484, 0.0421637 ]),
 'rank_test_score': array([4, 1, 2, 3], dtype=int32)}

In [205]:
results_r=pd.DataFrame(classifier_r.cv_results_)

In [206]:
results_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001958,0.000340,0.001309,0.000140,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,4
1,0.002027,0.000040,0.001390,0.000030,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.001962,0.000071,0.001319,0.000039,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,2
3,0.001769,0.000058,0.001175,0.000022,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,3

In [207]:
results_r[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0       30          rbf         0.960000
1       10          rbf         0.980000
2       20          rbf         0.966667
3       20       linear         0.966667

In [208]:
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.naive_bayes import GaussianNB

In [209]:
base_learners = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svc', SVC(probability=True, kernel='rbf', random_state=42)),
    ('lr', LogisticRegression(max_iter=1000))
]

In [210]:
meta_learner = KNeighborsClassifier()

In [211]:
stacking_clf = StackingClassifier(estimators=base_learners, final_estimator=meta_learner, cv=5)

In [212]:
stacking_clf.fit(X_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=KNeighborsClassifier())

In [213]:
y_pred = stacking_clf.predict(X_test)

In [214]:
accuracy = accuracy_score(y_test, y_pred)

In [215]:
accuracy

1.0

In [216]:
confusion_matrix(y_test, y_pred)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 16]])

In [217]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n      setosa       1.00      1.00      1.00        19\n  versicolor       1.00      1.00      1.00        15\n   virginica       1.00      1.00      1.00        16\n\n    accuracy                           1.00        50\n   macro avg       1.00      1.00      1.00        50\nweighted avg       1.00      1.00      1.00        50\n'

In [218]:
from sklearn.ensemble import RandomForestClassifier

In [219]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, max_depth=None)

In [220]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [221]:
y_pred_rf =rf_model.predict(X_test)

In [223]:
accuracy_rf = accuracy_score(y_test, y_pred_rf)

In [224]:
accuracy_rf

0.98