In [105]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [106]:
df=sns.load_dataset("iris")

In [107]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [108]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [109]:
df['species'].unique()

<ArrowStringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [110]:
from sklearn.model_selection import train_test_split

In [111]:
X=df.drop('species', axis=1)
y=df['species']

In [112]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [113]:
from sklearn.neighbors import KNeighborsClassifier

In [114]:
model_knn=KNeighborsClassifier(n_neighbors=13)

In [115]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [116]:
model_knn.score(X_test, y_test)

1.0

In [117]:
from sklearn.svm import SVC

In [118]:
model_svm=SVC(gamma='auto')

In [119]:
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [120]:
model_svm.score(X_test, y_test)

1.0

## Now Let's Use Grid Search CV

In [121]:
from sklearn.model_selection import GridSearchCV

In [122]:
classifier = GridSearchCV((model_svm), {
    'C':[10, 20, 30],
    'kernel':['rbf', 'linear']
}, cv =5, return_train_score=False)

In [123]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [10, 20, 30], 'kernel': ['rbf', 'linear']})

In [124]:
classifier.cv_results_

{'mean_fit_time': array([0.00215058, 0.00142832, 0.00154886, 0.00145535, 0.00154052,
        0.00150137]),
 'std_fit_time': array([3.55907607e-04, 2.99286644e-05, 9.54854473e-05, 1.12485006e-04,
        6.14373915e-05, 7.21767349e-05]),
 'mean_score_time': array([0.00129719, 0.00094008, 0.0011292 , 0.00096102, 0.00102262,
        0.00096178]),
 'std_score_time': array([1.11102076e-04, 1.12142936e-05, 3.05431951e-04, 6.55421997e-05,
        5.96655344e-05, 7.69320270e-06]),
 'param_C': masked_array(data=[10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 1.        , 0.96666667, 1.        , 0.96666667,
        1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.9       , 0.9       , 0.9       , 0.9       ,
        0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.93333333,
        0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.97333333, 0.96666667, 0.96666667, 0.96      ,
        0.96      ]),
 'std_test_score': array([0.01632993, 0.03887301, 0.03651484, 0.0421637 , 0.03887301,
        0.04898979]),
 'rank_test_score': array([1, 2, 3, 4, 5, 5], dtype=int32)}

In [125]:
results=pd.DataFrame(classifier.cv_results_)

In [126]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002151,0.000356,0.001297,0.000111,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.001428,0.000030,0.000940,0.000011,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
2,0.001549,0.000095,0.001129,0.000305,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
3,0.001455,0.000112,0.000961,0.000066,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
4,0.001541,0.000061,0.001023,0.000060,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,5
5,0.001501,0.000072,0.000962,0.000008,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,5

In [127]:
results[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       10       linear         0.973333
2       20          rbf         0.966667
3       20       linear         0.966667
4       30          rbf         0.960000
5       30       linear         0.960000

In [128]:
from sklearn.model_selection import RandomizedSearchCV

In [129]:
classifier_r = RandomizedSearchCV((model_svm), {
    'C':[10, 20, 30],
    'kernel':['rbf', 'linear']
},n_iter=4, cv =5, return_train_score=False)

In [130]:
classifier_r.fit(X, y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [131]:
classifier_r.cv_results_

{'mean_fit_time': array([0.00209522, 0.00158501, 0.00299048, 0.00216799]),
 'std_fit_time': array([7.76272514e-04, 8.25725842e-05, 9.12810594e-04, 2.17854650e-04]),
 'mean_score_time': array([0.00118532, 0.00129962, 0.00181751, 0.00139942]),
 'std_score_time': array([0.00028495, 0.0004373 , 0.0003071 , 0.00010598]),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[20, 10, 10, 20],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'C': 20},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'linear', 'C': 10},
  {'kernel': 'rbf', 'C': 20}],
 'split0_test_score': array([1.        , 0.96666667, 1.        , 0.96666667]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667, 0.9       , 0.9       ]),
 'split3_test_score': array([0.93333333, 0.96666667, 0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1.]),
 'mean_test_score': array([0.96666667, 0.98      , 0.97333333, 0.96666667]),
 'std_test_score': array([0.0421637 , 0.01632993, 0.03887301, 0.03651484]),
 'rank_test_score': array([4, 1, 2, 3], dtype=int32)}

In [132]:
results_r=pd.DataFrame(classifier_r.cv_results_)

In [133]:
results_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002095,0.000776,0.001185,0.000285,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
1,0.001585,0.000083,0.001300,0.000437,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002990,0.000913,0.001818,0.000307,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
3,0.002168,0.000218,0.001399,0.000106,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3

In [134]:
results_r[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0       20       linear         0.966667
1       10          rbf         0.980000
2       10       linear         0.973333
3       20          rbf         0.966667